---
- block: # Configure hostname
  - name: Configure hostname
    hostname:
      name: "{{ inventory_hostname }}"
    when: host_preparation_is_config_hostname | bool

  - name: Configure hosts file
    lineinfile:
      dest: /etc/hosts
      state: present
      regexp: "^{{ ansible_host }} "
      line: "{{ ansible_host }} {{ inventory_hostname }}"
    when: host_preparation_is_config_hostname | bool

  tags:
    - host-preparation-configure-hostname
