---
- name: Change sshd port
  lineinfile:
    dest: "{{ host_preparation_sshd_config }}"
    regexp: ^Port .*
    line: "Port {{ host_preparation_sshd_port }}"
  when: host_preparation_is_config_sshd | bool
  notify: Restart sshd service
  tags:
    - host-preparation-configure-sshd

- name: Force to listen to only ssh ip address
  lineinfile:
    dest: "{{ host_preparation_sshd_config }}"
    regexp: ^ListenAddress .*
    line: "ListenAddress {{ ansible_host }}"
  when: host_preparation_sshd_listen_only_ssh_interface | bool
  notify: Restart sshd service
  tags:
    - host-preparation-configure-sshd
